LIS/LISAv2

- Testscripts/Linux/enablePasswordLessRoot.sh
- Testscripts/Linux/enableRoot.sh
This will unblock performance tests.
> Added scripts to enable root user

- Libraries/Azure.psm1
- Libraries/CommonFunctions.psm1
- XML/VMConfigurations/PerformanceTestsConfigurations.xml
- XML/VMConfigurations/SmokeTestsConfigurations.xml
> Removed legacy XML tag "HostedService"

- Utilities/CheckTestPipelineRemotely.sh
- Utilities/LaunchTestPipelineRemotely.sh
This is local environmental test launcher for remote execution. It should have 3rd party binary tools in Tools folder in advance. Downloading link changes to Copying command.  (218 ~ 219)
Ohters are changing from space to tab only.
> jq file copying location to local

- RunTests.ps1
This is area for binary tools access
> Logging changed

- AutomationManager.ps1
- AzureTestSuite.ps1
- README.md
- RunTests.ps1
After we enabled Hyper-V platform as supported one in LISAv2, this PR shows changes from document/top-level scripts including generalized variable names and logs. 
Also include coding style changes from space to tab.
Removed un-used variables. 
Validation completed in the job, Microsoft-Test-Execution-Pipeline/200 and local environment.
> Updated scripts and document for 2nd supported platform

- XML/TestCases/StressTests.xml
> Stress category format fix

- RunTests.ps1
> Revert "Fix the case XMLSecretFile is not set, and only copy back test results"

- Libraries/Test-Framework.psm1
- Testscripts/Linux/utils.sh
- Testscripts/Linux/verify-ifup-nics.sh
- XML/TestCases/FunctionalTests-SRIOV.xml
Fixes issue: https://github.com/LIS/LISAv2/issues/137
> azure: Fix SRIOV test VERIFY-IFUP-NICS-SRIOV

- XML/TestCases/PerformanceTests.xml
Removed extra `testScript` element from XML definition
> Fixed : PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-SRIOV

- Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
Fio test was reading wrong log file
> FIO : Minor fix

- Libraries/CommonFunctions.psm1
- Utilities/UploadFilesToStorageAccount.ps1
1. Fixed Upload files script as per new version of Azure powershell.
2. Fixed issue in Write-Log, if LogDir is empty.
> Minor fixes

- XML/TestCases/CommunityTests.xml
> Tag always should be lowercase

- XML/TestCases/CommunityTests.xml
> XML tag format correction

- Documents/How-to-use.md
Recommended function name style: Function_Name (), F and N should be Upper letter connected with underscore character.
> Added function name style guideline

- Documents/How-to-use.md
- XML/TestCases/BVT.xml
- XML/TestCases/CommunityTests.xml
- XML/TestCases/FunctionalTests-SRIOV.xml
- XML/TestCases/Other.xml
- XML/TestCases/PerformanceTests.xml
Add the current tags and its format
> Add Tagging guideline

- Get-LISAv2Statistics.ps1
list out test cases
show the counts of test cases per platform
tag information
> Add a new PS script displaying test cases

- Libraries/Framework.psm1
- RunTests.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests-DPDK.xml
- XML/TestCases/PerformanceTests-DPDK.xml
- XML/TestCases/PerformanceTests.xml
Syntax :
```
RunTests.ps1 -Platform <Platform>
-Area <Area>
.
.
.
-CustomParameters "ReplaceThis1=ReplaceWith1;ReplaceThis2=ReplaceWith2"
```
Note: Multiple replace operations can be done using sign - semicolumn (";").
Replaceable parameters needs to be defined in ".\XML\Other\ReplaceableTestParameters.xml" before using them.
> New LISAv2 feature : Replaceable test parameters

- Documents/How-to-use.md
Used case insensitive or irregular pattern of each name. In order to publish our all data in PowerBI or Graph update, we should use the same distro short name.
> Add distro short name and test result term

- XML/TestCases/FunctionalTests-Synthetic.xml
This issue was introduced in PR#102.
> Fixed missing file bug in a test case.

- Libraries/Test-Framework.psm1
--This fixes the remote host test runs by adding ComputerName param to
the existing cmdlets.
--Added multiple setupscript run
--Added a new testParam that can be sent to the guest - ipv4
> framework: fix remote server run

- Libraries/CommonFunctions.psm1
Fixes the issue introduced in PR #202 
(Bug #209)
> Fixed issue where RemoteCopy is returning empty string.

- Testscripts/Linux/KDUMP-Config.sh
- Testscripts/Linux/KDUMP-Execute.sh
- Testscripts/Linux/KDUMP-NFSconfig.sh
- Testscripts/Linux/KDUMP-Results.sh
- Testscripts/Windows/KDUMP-TestScript.ps1
- XML/TestCases/FunctionalTests.xml
After the review all the tests were run, having the following results:
HyperV: All 6 PASS (Ubuntu 18.04, CentOS 7.5)
Azure: All 5 PASS (Ubuntu 18.04, RedHat 7.5)
> HyperV, Azure: kdump tests

- Testscripts/Linux/InstallCUDADrivers.sh
- Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
1. Reference : https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
2. Fixed issue where, test case was not showing the sub-test results in test summary.
> Updated script with latest CUDA version.

- AutomationManager.ps1
- Libraries/CommonFunctions.psm1
- Libraries/Framework.psm1
- Libraries/HyperV.psm1
- Libraries/Test-Framework.psm1
- RunTests.ps1
Feature request https://github.com/LIS/LISAv2/issues/211
> Implement Generation 2 Hyper-V VM support

- Utilities/Get-LISAv2Statistics.ps1
Move Get-LISAv2Statistics.ps1 under Utilities
Also exclude other.xml file.
> Relocate statistics report file in Utilities folder

- Testscripts/Linux/STOR-Verify-Sector-Size.sh
- XML/TestCases/FunctionalTests.xml
VHD under test **Centos_7.5_x64.vhd**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:3
1. STORAGE-VHDX-VERIFY-SECTORSIZE : PASS : 3.16
VHD under test **ubuntu_18.04.vhd**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:5
1. STORAGE-VHDX-VERIFY-SECTORSIZE : PASS : 5.1
> hyper-v : Added 1 Storage TC

- Libraries/HyperV.psm1
If the snapshots are not removed, the VHDs will be left on the disk after vm deletion, as the *.avhdx are the only one removed.
On localhost, do not use invoke command with computername set, as it might fail on non domain computers.
> hyper-v: Remove snapshots and not leak vhds

- Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
- Testscripts/Linux/STOR_VHDXResize_ReadWrite.sh
- Testscripts/Windows/STOR-VHDX-RESIZE-BASIC.ps1
- XML/TestCases/FunctionalTests.xml
ICA test run on 10/16/2018 10:21:49
VHD under test disco.vhdx
Total Executed TestCases        6 (       6 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:46
1. VHDX-RESIZE-TO-BIGGER512 : PASS : 10.22
2. VHDX-RESIZE-TO-BIGGER4096 : PASS : 6.4
3. VHDX-RESIZE-TO-BIGGER512-FIXED-IDE : PASS : 7.48
4. VHDX-RESIZE-TO-BIGGER512-DYNAMIC-IDE : PASS : 7.23
5. VHDX-RESIZE-TO-SMALLER512 : PASS : 7.09
6. VHDX-RESIZE-TO-SMALLER4096 : PASS : 7.79
> Hyper-V: 6 VHDx Resize TCs

- Libraries/CommonFunctions.psm1
- Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
- Testscripts/Linux/STOR_VSS_StopNetwork.sh
- Testscripts/Linux/utils.sh
- Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
- Testscripts/Windows/PRODUCTION-CHECKPOINT-FAILBACK.ps1
- Testscripts/Windows/PRODUCTION-CHECKPOINT-ISO-NONETWORK.ps1
- Testscripts/Windows/PRODUCTION-CHECKPOINT-PARTITION.ps1
- Testscripts/Windows/PRODUCTION-CHECKPOINT-iSCSI.ps1
- Testscripts/Windows/PRODUCTION-CHECKPOINT.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests.xml
- PRODUCTION-CHECKPOINT
- PRODUCTION-CHECKPOINT-EXT3
- PRODUCTION-CHECKPOINT-IDE_SCSI
- PRODUCTION-CHECKPOINT-ISO-NONETWORK
- PRODUCTION-CHECKPOINT-3CHAIN-VHD
- PRODUCTION-CHECKPOINT-iSCSI
> Hyper-V: Added 6 Production checkpoint tests

- Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
- Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
- XML/TestCases/FunctionalTests.xml
VHDX-RESIZE-GROW-FILESYSTEM-512
VHDX-RESIZE-GROW-FILESYSTEM-4096
> Hyper-V: Added 2 VHDx Resize tests

- Libraries/CommonFunctions.psm1
- Testscripts/Linux/NET-Verify-Boot-NoNIC.sh
- Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
- Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
- Testscripts/Windows/NET-HotAdd-MultiNIC.ps1
- Testscripts/Windows/NET-HotAddRemove-Max-NIC.ps1
- XML/TestCases/FunctionalTests.xml
VHD under test **ubuntu_18.04_x64_gen2vm.vhdx**
Total Executed TestCases        4 (       4 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:9
1. NET-HOT-ADD-MULTINIC : PASS : 2.15
2. NET-HOT-REMOVE-MULTINIC : PASS : 0.65
3. NET-BOOT-NONIC-HOT-ADD-NIC : PASS : 2.33
4. NET-HOT-ADD-REMOVE-MAXNIC : PASS : 4.07
> Hyper-V : Added 4 Network Gen2 VM tests

- Libraries/CommonFunctions.psm1
- Libraries/Test-Framework.psm1
- Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
- Testscripts/Linux/enableRoot.sh
- Testscripts/Linux/fio_jason_parser.sh
- Testscripts/Linux/perf_fio.sh
- Testscripts/Linux/perf_iperf3.sh
- Testscripts/Linux/perf_lagscope.sh
- Testscripts/Linux/perf_netperf.sh
- Testscripts/Linux/perf_ntttcp.sh
- Testscripts/Linux/utils.sh
- Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
- Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
- Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
- Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
Run below cases against CoreOS CoreOS Stable Latest and canonical ubuntuserver 18.04-lts Latest
PERF-NETWORK-TCP-NETPERF-SINGLE-PPS-Synthetic
PERF-NETWORK-TCP-NETPERF-MAX-PPS-Synthetic
PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT-Synthetic
PERF-STORAGE-4K-IO
PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-Synthetic
PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP-Synthetic
> Support performance testing against CoreOS

- Libraries/CommonFunctions.psm1
Added Write-Output "yes" , before pscp or plink in order update host key in case it changed
> Fix : lisav2 fails when the ssh host key is not trusted #330

- Libraries/CommonFunctions.psm1
- Testscripts/Windows/CLEANUP-Backup-DISK.ps1
- Testscripts/Windows/SETUP-Backup-DISK.ps1
- Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
- XML/TestCases/FunctionalTests.xml
This Pull request covers SECUREBOOT-VSS  Testcase
ICA test run on 10/25/2018 14:08:26
VHD under test SecureBootGen2.vhdx
ARM Image under test  :  :  :
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:11
1. SECUREBOOT-VSS : PASS : 11.68
Logs can be found at .\TestResults\2018-25-10-19-38-26-5865
10/25/2018 14:20:07 : [INFO ] Creating 'HyperV-57209-buildlogs.zip' from '.\TestResults\2018-25-10-19-38-26-5865'
10/25/2018 14:20:07 : [INFO ] D:\secureboot\LISAv2\HyperV-57209-buildlogs.zip created successfully.
10/25/2018 14:20:07 : [INFO ] Copied : …
> Added new Secureboot testcase

- Testscripts/Linux/customKernelInstall.sh
Azure images don't include the binutils package, that is required for the source packages
Also contains indentation fixes.
PR tested on the staging environment.
> customKernelInstall: apt-update & install binutils required for kernel install

- Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
Created database table for syscall test results and updated script to upload results into database.
> Updated  Syscall test script to upload results into database.

- Libraries/CommonFunctions.psm1
- Testscripts/Windows/DM-CONFIGURE-MEMORY.ps1
- Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
- Testscripts/Windows/DM-HOTADD-STRESS-NG.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests.xml
1. DYNAMIC-MEMORY-HOT-ADD
2. DYNAMIC-MEMORY-HOTADD-STRESS-APP
3. DYNAMIC-MEMORY-STRESS-HOTADD-5SECONDS
4. DYNAMIC-MEMORY-STRESS-HOTADD-1SECOND
5. DYNAMIC-MEMORY-STRESS-LARGE-CHUNK
> Hyper-v: Dynamic Memory 5 test cases

- Libraries/CommonFunctions.psm1
- Testscripts/Linux/STOR_VSS_Disk_Fail.sh
- Testscripts/Linux/STOR_VSS_Disk_Stress.sh
- Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-DISKSTRESS.ps1
- Testscripts/Windows/STOR-VSS-Backup-Disable-Enable-VSS.ps1
- Testscripts/Windows/STOR-VSS-BackupRestore-Fail.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests.xml
This Pull Request covers below test-cases of VSS Backup
1)STOR-VSS-BACKUP-RESTORE-DISKSTRESS
2)STOR-VSS-BACKUP-DISABLE-ENABLE-VSS
3)STOR-VSS-BACKUP-RESTORE-FAIL
Please find below test result summary
ICA test run on 10/31/2018 12:39:38
VHD under test vss_tests.vhd
ARM Image under test  :  :  :
Total Executed TestCases        3 (       3 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:36
1. STOR-VSS-BACKUP-RESTORE-DISKSTRESS : PASS : 13.96
2. STOR-VSS-BACKUP-DISABLE-ENABLE-VSS : PASS : 13.57
3. STOR-VSS-BACKUP-RESTORE-FAIL : PASS : 8.79
> Hyper-V: Added 3 VSS-Backup test cases

- Run-LisaV2.ps1
- Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
- Utilities/AnalyseAllResults.ps1
No functional change, just a wording fix
> Fixed the typo in logging

- Utilities/Get-LISAv2Statistics.ps1
- XML/TestCases/FunctionalTests-InfiniBand.xml
Add Priority when collect test cases info.
Remove duplicated Priority section.
> Update code for Priority changed

- Testscripts/Linux/timesync_config.sh
- Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
- Testscripts/Windows/FCOPY-NEGATIVE.ps1
- XML/TestCases/BVT.xml
Before: 
VHD under test **ubuntu_18.04_x64_gen2vm.vhdx**
Total Executed TestCases           3 (          0 Pass,           1 Fail,           2 Abort)
Total Execution Time(dd:hh:mm) 0:0:27
1. BVT-NET-IFUP-IFDOWN : ABORTED : 25.44
2. FCOPY-NEGATIVE : FAIL : 0.42
3. TIMESYNC-BASIC : ABORTED : 1.85
After : 
VHD under test **ubuntu_18.04_x64_gen2vm.vhdx**
Total Executed TestCases        3 (       3 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:4 …
> Hyper-V: Fix gen2 VM automation issues

- Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
- XML/TestCases/BVT.xml
Azure run : 
ICA test run on 11/12/2018 12:56:46
ARM Image under test Canonical : **UbuntuServer : 18.04-LTS : latest**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:3
1. BVT-NET-IFUP-IFDOWN : PASS : 3.83
HyperV run : 
VHD under test **ubuntu_18.04_x64_gen2vm.vhdx**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:3
1. BVT-NET-IFUP-IFDOWN : PASS : …
> Fix Azure issue in PR377

- Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
- XML/TestCases/BVT.xml
> Revert "Fix Azure issue in PR377"

- UnitTests/PowerShell/Libraries.Azure.Tests.ps1
- UnitTests/PowerShell/Libraries.CommonFunctions.Tests.ps1
- UnitTests/PowerShell/Libraries.ExtensionLibrary.Tests.ps1
- UnitTests/PowerShell/Libraries.Framework-Azure.Tests.ps1
- UnitTests/PowerShell/Libraries.Framework-HyperV.Tests.ps1
- UnitTests/PowerShell/Libraries.HyperV.Tests.ps1
- azure-pipelines.yml
Also displays message that PSScriptAnalyzer was ran even when there are no warnings, previously there was no output
> unit_tests: Fixed pester tests

- Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
- XML/TestCases/BVT.xml
Fixed 2 issue : 
- exit of test script before finishing to run on VM 
- Azure run exception related to test location 
Azure run :
ICA test run on 11/12/2018 15:42:27
ARM Image under test Canonical **: UbuntuServer : 18.04-LTS : latest**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:7
1. BVT-NET-IFUP-IFDOWN : PASS : 7.03
Hyper-v run :
ICA test run on 11/12/2018 15:48:44
VHD under test **ubuntu_18.04_x64_gen2vm**
Total Executed TestCases        1 (       1 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:10
XML …
> Fixed issues from PR377 

- Testscripts/Windows/RUNTIME-MEM-CONFIGURE.ps1
- Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
- Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
- Testscripts/Windows/RUNTIME_MEM_HOTADD_REBOOT.ps1
- Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
- Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests.xml
Also contains code indentation changes
> Bug Fix for Run_time_memory_resize

- Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
The BVT-VERIFY-SHUTDOWN would try to upload files to the VM after it's shutdown, to collect logs.
This PR starts the VM after the test complete, for
1. log collecting
2. reuse the VM for other test
> Fix BVT-VERIFY-SHUTDOWN for log collecting

- AutomationManager.ps1
- AzureTestSuite.ps1
- Libraries/Azure.psm1
- Libraries/CommonFunctions.psm1
- Libraries/ExtensionLibrary.psm1
- Run-LisaV2.ps1
- Testscripts/Windows/BVT-VERIFY-RESTART.ps1
- Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
- Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
- Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
- Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
- Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
- Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
- Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
LISAv2 supports Azure Resource Manager only, the variable UseAzureResourceManager is not needed
> Remove global variable UseAzureResourceManager

- Testscripts/Windows/AddVhdxHardDisk.ps1
- Testscripts/Windows/STOR_VHDXRESIZE_BASICLM.ps1
- XML/TestCases/FunctionalTests.xml
This pull request covers VHDX-Reszie LiveMigration Testcase
Please find below test result summary
Test Run On           : 11/21/2018 11:17:09
VHD Under Test        : LiveMigrationGen1.vhdx
ARM Image Under Test  :  :  :  :
Total Time (dd:hh:mm) : 0:0:6
ID TestCaseName                                                 TestResult TestDuration(in minutes)
1 VHDX-RESIZE-LIVE-MIGRATION                                         PASS                 6.15
> Hyper-V: Added VHDX-Resize Live Migration test-case

- Testscripts/Linux/BVT-CORE-TIMESYNC-NTP.sh
Verified that it still works on fedore 28 : 
VHD Under Test        : fedora28_gen2.vhdx
Total Time (dd:hh:mm) : 0:0:2
1 BVT-CORE-TIMESYNC-NTP                                              PASS                  2.5
> BVT-TimeSync_NTP.sh: skip test if ntp is not supported

- Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
- Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
- Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
- Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
- Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
- Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
- Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
- Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
- Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
- Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
- Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
- Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
- Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
- Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
- Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
- Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
- Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
Before change, below case abort for path issue.
After change - 
Test Run On           : 11/22/2018 14:07:14
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Total Time (dd:hh:mm) : 0:0:25
1 PERF-NETWORK-TCP-NETPERF-SINGLE-PPS-Synthetic                      PASS                20.79 
Rx Average PPS : 4970 
Rx Minimum PPS : 3890 
Rx Maximum PPS : 6408
> Modify relative path to absolute path.

- Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
On CentOS, you cannot issue any ssh commands after the azure deprovision.
This PR fixes that problem by making sure it runs the bionic fix only on Ubuntu
after patch applied:
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 11/23/2018 16:52:39
[azure] ARM Image Under Test  : OpenLogic : CentOS : 7.5 : latest
[azure] Total Test Cases      : 1 (1 Pass, 0 Fail, 0 Abort)
[azure] Total Time (dd:hh:mm) : 0:0:5
[azure] XML File              : TestConfiguration
[azure] 
[azure]    ID TestCaseName                                                 TestResult TestDuration(in minutes) 
[azure] ------------------------------------------------------------------------------------------------------
[azure]     1 CAPTURE-VHD-BEFORE-TEST                                            PASS …
> CAPTURE-VHD-BEFORE-TEST: Fix CentOS VHD capture

- Testscripts/Linux/SR-IOV-Utils.sh
- Testscripts/Linux/stress_web.sh
- Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
- Testscripts/Windows/STRESS-Web.ps1
- XML/TestCases/StressTests.xml
> Azure, Hyper-V: Add new test case for web stress test with http_load

- JenkinsPipelines/Scripts/DeletePartnerFiles.ps1
- JenkinsPipelines/Scripts/DetectTestRegions.ps1
- JenkinsPipelines/Scripts/GetPartnerStorageUsage.ps1
- JenkinsPipelines/Scripts/InspectCustomKernel.ps1
- JenkinsPipelines/Scripts/JenkinsTestSelectionMenuGenerator.ps1
- JenkinsPipelines/Scripts/PrepareEnvOfNestedVMsTestOnHyperv.ps1
- JenkinsPipelines/Scripts/UpdateAzureRegionAndVMSizes.ps1
- JenkinsPipelines/Scripts/UpdatePublisherImages.ps1
Fixes all remaining scripts after initial PR #425.
Contains minor typo and indentation fixes.
> penguinator: fixed remaining LogFileName errors

- JenkinsPipelines/Run-Linux-Tests.groovy
This is required in order to specify Premium storage required for storage performance.
Otherwise, this defaults to Standard storage, as by default if not specified at all.
> penguinator: Added StorageAccount parameter

- Libraries/HyperV.psm1
If the OsVHD parameter is given as an SMB (UNC) path and a test case using multiple hyperv hosts is run (for example, all the performance ones), the VM creation will fail due to SMB issues.
This patch uses full UNC paths to make sure the SMB OsVHD is properly copied on the other hyperv nodes.
> hyperv: Fix SMB vhds on multiple hosts

- XML/TestCases/FunctionalTests.xml
Remove 'CORE' from testName.
Change heart_beat to hearbeat.
> Functional tests: Remove CORE- tag

- Testscripts/Linux/CORE-LogCollector.sh
Addressing issue #480 
Before fix :
[azure] 12/03/2018 19:26:52 : [INFO ] Collection Operating System Logs.....
[azure] Ubuntu 18.04.1 LTS \n \l
[azure] Operating system Log process finished...
[azure] Collecting Waagent Details....
[azure] dpkg-query: package 'walinuxagent' is not available
[azure] Use dpkg --info (= dpkg-deb --info) to examine archive files,
[azure] and dpkg --contents (= dpkg-deb --contents) to list their contents.
[azure] Collecting Microsoft Linux Integration Service Data...
**[azure] modinfo: ERROR: missing module or filename.**
[azure] Collecting Microsoft Linux Integration Service Data Finsished...
[azure] Collecting Disk and Memory Data
[azure] Collecting Disk and Memory Data Finished...
[azure] Collecting Processor Data...
[azure] Collecting Processor Data …
> Azure: fix modinfo error 

- AutomationManager.ps1
- Libraries/Azure.psm1
- Libraries/LISAV2-Framework.psm1
- Libraries/LogProcessing.psm1
- Libraries/XmlProcessing.psm1
- Utilities/CheckImageUpdate.ps1
Run test when specify SASUrl / OSVHD / ARMIMAGE against Azure
Run test against HyperV 
All pass.
> Support run test case against SASURL and update report format.

- Libraries/LISAV2-Framework.psm1
Reverts LIS/LISAv2#487
@juhlee-microsoft  please don t merge it before all agree is fine.
> Revert "Remove enable root for each case."

- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/PerformanceTests.xml
This change parameterizes BUFFER-LENGTHS for the developer perf comparison pipeline.
> perf_sriov: added custom buffer length parameter

- Libraries/Azure.psm1
- Testscripts/Linux/perf_ntttcp.sh
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/PerformanceTests.xml
Partially addresses issue: https://github.com/LIS/LISAv2/issues/499
> Fix transient azure api failures and parameterize ntttcp connections

- XML/TestCases/PerformanceTests.xml
As requested, q depth max value was changed from 2048 to 256. No further code changes are needed
> storage perf: Changed max q depth value

- Libraries/Azure.psm1
- Libraries/CommonFunctions.psm1
- Testscripts/Linux/customKernelInstall.sh
- Testscripts/Linux/utils.sh
Tested on Ubuntu 16.04, Ubuntu 18.04 and CentOS 7.5
> Fix installing linux upstream kernel with -CustomKernel

- Testscripts/Linux/CORE-LogCollector.sh
Output after fix : 
**Centos:**
[azure] 12/14/2018 07:57:41 : [INFO ] Collecting Operating System Logs.....
[azure] \S
[azure] Kernel \r on an \m
[azure] Operating system Log process finished...
[azure] Collecting Waagent Details....
[azure] Collecting Microsoft Linux Integration Service Data...
[azure] hv_netvsc module: 3.10.0-862.11.6.el7.x86_64
[azure] hv_storvsc module: 3.10.0-862.11.6.el7.x86_64
[azure] scsi_transport_fc module: 3.10.0-862.11.6.el7.x86_64
[azure] hv_vmbus module: 3.10.0-862.11.6.el7.x86_64
[azure] Collecting Microsoft Linux Integration Service Data Finished...
[azure] Collecting Disk and Memory Data
[azure] Collecting Disk and Memory Data Finished...
[azure] Collecting Processor Data...
[azure] Collecting Processor Data Finished...
[azure] Collecting Network Data... …
> Fix CORE-LogCollector.sh for multiple distros

- Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Official documentation recommends to clear the shell history.
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic
This is useful for custom modified vhd images that might not be properly cleaned up.
---
Test results:
ID TestCaseName                                                 TestResult TestDuration(in minutes)
1 CAPTURE-VHD-BEFORE-TEST                                            PASS                 5.83
ID TestCaseName                                                 TestResult TestDuration(in minutes)
1 BVT-VERIFY-BASH-HISTORY …
> CAPTURE-VHD-BEFORE-TEST.ps1: small fixes and code cleanup

- Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
This patch changes how the fio performance results are uploaded
to the database, by squashing the results mode results by qdepth.
Previous behaviour was to insert a row in the database for each
mode (randread, randwrite, read, write) that have the same qdepth.
Current behaviour is to insert one row in the database for all
modes that have the same qdepth.
> perf_fio: squash database results by qdepth

- Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
- Testscripts/Windows/KDUMP-TestScript.ps1
Fix cases of TestCategory Community Area Xfstesting-cifs
Fix cases of TestCategory Functional Area KDUMP after disable root
> Fix Xfstesting-cifs and KDUMP test case issues

- Testscripts/Linux/BVT-CORE-TIMESYNC-NTP.sh
- Testscripts/Linux/KDUMP-Config.sh
Test Run On           : 01/08/2019 10:08:16
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Total Test Cases      : 5 (5 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:38
1 KDUMP-CRASH-SINGLE-CORE                                            PASS                10.44 
2 KDUMP-CRASH-SMP                                                    PASS                 6.08 
3 KDUMP-CRASH-AUTO-SIZE                                              PASS                 5.68 
4 KDUMP-CRASH-DIFFERENT-VCPU …
> kdump tests: fix packages definition

- Libraries/CommonFunctions.psm1
- Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
- Testscripts/Windows/FCOPY-LARGE-FILE.ps1
- Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
Affected Tests: 
FCOPY-DISABLE-ENABLE
FCOPY-REPEATED-DELETE
FCOPY-LARGE-FILE 
Test results:
Total Test Cases      : 3 (3 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:23
1 FCOPY-LARGE-FILE                                                   PASS                 9.45 
2 FCOPY-REPEATED-DELETE                                              PASS                 5.14 
3 FCOPY-DISABLE-ENABLE                                               PASS                 9.08
> Remove Send-CommandToVM and fix Mount-Disk function to run as sudo 

- Utilities/Clean-OldHypervVMs.ps1
> Revert "Clean-OldHypervVMs.ps1: fix invalid char encoding"

- Testscripts/Linux/perf_ntttcp.sh
> NTTTCP test fix (bug introduced in PR #546)

- Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
Test Results:
1 PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-Synthetic                             PASS               124.54 
Buffer=1K Connections=1 : ClientTxGbps=1.31 ServerRxGbps=1.31 UDPLoss=0.28% 
Buffer=1K Connections=2 : ClientTxGbps=2.47 ServerRxGbps=2.45 UDPLoss=0.87% 
Buffer=1K Connections=4 : ClientTxGbps=3.92 ServerRxGbps=3.83 UDPLoss=2.49% 
Buffer=1K Connections=8 : ClientTxGbps=3.74 ServerRxGbps=3.7 UDPLoss=1.79% 
Buffer=1K Connections=16 : ClientTxGbps=3.74 ServerRxGbps=3.28 UDPLoss=9.62% 
Buffer=1K Connections=32 : ClientTxGbps=3.65 ServerRxGbps=3.34 UDPLoss=7.91% 
Buffer=1K Connections=64 : ClientTxGbps=3.62 ServerRxGbps=3.05 UDPLoss=16.5% 
Buffer=1K Connections=128 : ClientTxGbps=2.84 ServerRxGbps=2.72 UDPLoss=4.9% 
Buffer=1K Connections=256 : ClientTxGbps=1.04 …
> Perf: PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-Synthetic/SRIOV fix

- Testscripts/Linux/Ethtool-Check-Statistics.sh
- Testscripts/Linux/NET-Copy-Both-Ways.sh
- Testscripts/Linux/NET-Copy-Large-File.sh
- Testscripts/Linux/NET-Jumbo-Frames.sh
- Testscripts/Linux/NET-Multicast.sh
- Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
Affected Test Cases : 
1. NET-EXTERNAL
2. NET-INTERNAL
3. NET-CHANGE-INTERNAL-NIC
4. NET-JUMBO-FRAMES
5. NET-COPY-LARGE-FILE
6. NET-COPY-FILE-DIFFERENT-MTU
7. NET-COPY-BOTH-WAYS
8. NET-VXLAN
9. NET-MULTICAST
10. ETHTOOL-CHECK-STATISTICS
Verification : 
```
Test Run On           : 01/25/2019 14:57:40
VHD Under Test        :  ubuntu_18.04.1.vhdx
Total Time (dd:hh:mm) : 0:0:11
1 NET-JUMBO-FRAMES                                                                  PASS …
```
>  Fix SETUP-Inject-IP-Constants.ps1 and related testcases after root removal

- Libraries/CommonFunctions.psm1
> Fix issue - custom-kernel: Install fails if the VMs have a static name

- Testscripts/Linux/SetupRDMA.sh
SetupRDMA should have new part for MVAPICH verification update
> Updated verification part for MVAPICH

- XML/TestCases/FunctionalTests.xml
Verification Tests : 
```
Test Run On           : 01/31/2019 13:55:52
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Time (dd:hh:mm) : 0:0:3
1 TIMESYNC-BASIC                                                                    PASS                 1.19 
```
```
Test Run On           : 01/31/2019 14:20:11
ARM Image Under Test  : RedHat : RHEL : 7-RAW : 7.5.2018050901
Total …
```
> Add TIMESYNC-BASIC on Azure

- LISAv2-Framework.psm1
- Libraries/TestHelpers.psm1
- Libraries/TestLogs.psm1
- README.md
- Run-LisaV2.ps1
- TestControllers/WSLController.psm1
- TestProviders/WSLProvider.psm1
- XML/GlobalConfigurations.xml
- XML/TestCases/BVT.xml
- XML/TestCases/PerformanceTests.xml
Test command:
.\Run-LisaV2.ps1 -TestPlatform WSL -TestLocation XXX -RGIdentifier 'liztest' -XMLSecretFile XXX -TestNames "BVT-VERIFY-BOOT-ERROR-WARNINGS,PERF-GOLANG-BENCHMARK" -OsVHD 'https://aka.ms/wsl-ubuntu-1804' -DestinationOsVHDPath d:\lizzha\test
Test results:
Test Run On           : 01/30/2019 09:37:24
VHD Under Test        : https://aka.ms/wsl-ubuntu-1804
Total Test Cases      : 2 (2 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:8
1 BVT-VERIFY-BOOT-ERROR-WARNINGS                                                    PASS …
> Added WSL as a new supported platform

- Libraries/CommonFunctions.psm1
- TestProviders/HyperVProvider.psm1
On HyperV, the setup scripts should not be run on the dependency vms.
Without this patch, all the HyperV SRIOV multivm setup tests fail.
Execution tested:
```
1 SRIOV-MULTICAST                                                                   PASS                 11.2 
Logs can be found at C:\LISAv2\TB12\TestResults\2019-06-02-00-29-31-0279
```
Azure bvt:
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 02/06/2019 08:33:11
[azure] ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
[azure] Test Category         : BVT …
```
> hyperv: run test script on non-dependency vms

- XML/AzureVMSizeToHyperVMapping.xml
This fixes https://github.com/LIS/LISAv2/issues/702
> Fix SRIOV-VERIFY-VF-MAX-CONNECTION

- Testscripts/Linux/xfstesting.sh
- SLES support was added
- Exit code fix
Test Run On           : 02/06/2019 14:18:51
VHD Under Test        : 283-sles15-gen1_2-v20190128.vhd
Total Test Cases      : 4 (4 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:1:59
1 NVME-FILE-SYSTEM-VERIFICATION-GENERIC                                             PASS                38.93
2 NVME-FILE-SYSTEM-VERIFICATION-XFS                                                 PASS                29.88
3 NVME-FILE-SYSTEM-VERIFICATION-EXT4                                                PASS …
> FILESYSTEM-TESTS: Added SLES support

- Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
An extra step was added in the Powershell script after all VMs have rebooted. A check for the modules will be made on each VM and if any ismissing, a reboot will be performed. We have 4 retries/VM. If after 4 retries IB is not up (modules are missing), then the test will be aborted.
e.g.
02/08/2019 14:37:39 : [INFO ] IB is initialized in client-vm-8
.....
02/08/2019 14:37:41 : [WARN ] IB is NOT initialized in client-vm-9
02/08/2019 14:37:42 : [INFO ] Triggering Restart-client-vm-9...
02/08/2019 14:37:42 : [INFO ] Waiting until VMs restart...
......
> IB: Added reboot if IB is not active

- Testscripts/Windows/DM-HOTADD-EATMEMORY.ps1
- Testscripts/Windows/DM-REMOVE-THEN-PRESSURE.ps1
- XML/Other/ReplaceableTestParameters.xml
- XML/TestCases/FunctionalTests-DynamicMemory.xml
Added 3 Testcases : 
- DYNAMIC-MEMORY-HOT-REMOVE-THEN-PRESSURE
- DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-SMP
- DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-UP
Note : 
- DYNAMIC-MEMORY-HOT-REMOVE-THEN-PRESSURE   case covers bug https://bugzilla.redhat.com/show_bug.cgi?id=1065107, verify that load average value of top command is smaller than 1 when dynamic memory is enabled.
- DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-UP and DYNAMIC-MEMORY-HOT-ADD-EAT-MEM-SMP , cover https://bugzilla.redhat.com/show_bug.cgi?id=1361245 and regression bug https://bugzilla.redhat.com/show_bug.cgi?id=1662277
Verification Tests : 
```
Test Run On           : 02/11/2019 09:54:16
Total Test Cases      : 3 (3 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:28
ID …
```
> Add 3 new DYNAMIC-MEMORY testcases

- LISAv2-Framework.psm1
LISAv2 will first save a list with all the current global variables (before anything is executed).
At the end of the run, another list will be saved.
In the end, all variables that can be found exclusively in the last list will be removed, except for lastexitcode and error.
Fixes issue: https://github.com/LIS/LISAv2/issues/717
> Framework: fix global variable cleanup

- Libraries/HyperV.psm1
**Fixes** https://github.com/LIS/LISAv2/issues/733
> Fixed: LISAv2 was checking for IP in infinite loop after VM checkpoint

- Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
Due to recent changes in the framework and how the result is handled, the script started to throw an exception. This was fixed
..........
02/15/2019 09:09:30 : [INFO ] END OF TEST SCRIPT SUMMARY ~~~~~~~~~~~~~~~
02/15/2019 09:09:30 : [INFO ] Test Completed.
02/15/2019 09:09:30 : [INFO ] Test Result: @{TestResult=PASS; TestSummary=}
02/15/2019 09:09:30 : [ERROR] EXCEPTION: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
02/15/2019 09:09:30 : [ERROR] Source: Line 162 in script .\Testscripts\Windows\SRIOV-RUN-COMMON-TEST.ps1.
.................
Test Run On           : 02/15/2019 09:05:37
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-DAILY-LTS : latest
Total Test Cases      : 1 (0 …
> SRIOV-RUN-COMMON-TEST.ps1: Exception fix

- Libraries/Azure.psm1
Also refactored code to show errors with Write-LogErr.
> Azure: Added Resource Group usage check in Validate-SubscriptionUsage()

- LISAv2-Framework.psm1
- Libraries/CommonFunctions.psm1
- Run-LisaV2.ps1
- TestControllers/TestController.psm1
**How to use?**
`RunLISAv2.ps1 -ExcludeTests "TEST_NAME1,TEST_NAME2" -TestPlatform Azure
-TestCategory "Functional"`
In the above example, LISAv2 will collect all the Azure tests from
Functional Category but it will skip- TEST_NAME1 and TEST_NAME2.
Addresses: https://github.com/LIS/LISAv2/issues/728
**Logs**
```
PS C:\GitHub\LISAv2> .\Run-LisaV2.ps1 -TestPlatform Azure -TestLocation centralus -RGIdentifier SS -ARMImageName "Canonical UbuntuServer 16.04-LTS latest" -XMLSecretFile "C:\GitHub\LISAv2\XML\AzureSecrets.xml" -TestNames "BVT-VERIFY-DEPLOYMENT-PROVISION,BVT-VERIFY-DEPLOYMENT-PROVISION-SRIOV" -ExcludeTests BVT-VERIFY-DEPLOYMENT-PROVISION-SRIOV
WARNING: The names of some imported commands from the module 'CommonFunctions' include 02/13/2019 16:49:57 : [INFO ] Autogenerated test ID: …
```
> LISAv2 New Feature: "Support for excluding the tests"

- XML/TestCases/FunctionalTests-InfiniBand.xml
> Renamed IB test cases by omitting VERIFY-

- Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
> Remove workaround for Ubuntu Bionic.

- Testscripts/Linux/STOR-Lis-Disk.sh
- Testscripts/Windows/STOR-VHDX-RESIZE-GROWSHRINK.ps1
- Testscripts/Windows/STORAGE-HotAdd.ps1
- XML/TestCases/FunctionalTests-Storage.xml
Issues addressed : 
**- Fixed sdcount to give correct output :** 
Sdcount now return correct devices count when compared to the ones in contants.sh 
**- Fixed failing vhdx cleanup :** 
Added cleanup script for vhd at the end of the testcases 
**- Fixed Hot Add vhd/vhdx :**
Test cases should use an existing controller and only hot add drives 
Affected Testcases : 
- VHDX-RESIZE-TO-BIGGER512
- VHDX-RESIZE-TO-BIGGER512-FIXED-IDE
- VHDX-RESIZE-GROWSHRINK-SCSI
- VHDX-RESIZE-GROWOVER2TB-SHRINK-SCSI-OFFLINE
- VHDX-RESIZE-GROWOVER2TB-SHRINK-IDE
- STORAGE-VHD-HOT-ADD-MULTI-DYNAMIC-SCSI
- STORAGE-VHDX-HOT-ADD-MULTI-DYNAMIC-SCSI
- STORAGE-VHDX-4K-HOT-ADD-MULTI-DYNAMIC-SCSI
```Test Run On           : 02/21/2019 18:02:57
VHD Under Test        : Ubuntu14.04.5-server.vhdx
Total Test Cases      : 8 (8 …
```
> Hyperv : Fix issues in Storage test cases

- Libraries/TestHelpers.psm1
> Capitalize the path per PR 790

- Testscripts/Windows/STRESS-Web.ps1
Test will now be skipped if distribution is not supported.
```
ARM Image Under Test  : RedHat : RHEL : 7.5 : 7.5.2018081519
1 STRESSTEST-WEB-PARALLEL-ACCESS                                                 SKIPPED                  1.9 
```
> STRESS-Web.ps1: Fix distribution check

- Libraries/IntegrationServiceLibrary.psm1
- Testscripts/Windows/Migrate-VM.ps1
- Testscripts/Windows/SECUREBOOT.ps1
- Testscripts/Windows/SET-SECUREBOOT.ps1
- Testscripts/Windows/SETUP-Backup-DISK.ps1
- Testscripts/Windows/STOR-VSS-3Chain-VHD-backup.ps1
- Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-DISKSTRESS.ps1
- Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
- Testscripts/Windows/STOR-VSS-Backup-Change-Hypervvssd.ps1
- Testscripts/Windows/STOR-VSS-Backup-Disable-Enable-VSS.ps1
- Testscripts/Windows/STOR-VSS-BackupRestore-Fail.ps1
- Testscripts/Windows/STOR-VSS-BackupRestore-ISO-NoNetwork.ps1
Partial fix for #763
Fixed Live Migration escaped outputs
Fixed Backup test cases failure and fix escaped  outputs
Fixed Secureboot escaped outputs
Issue # 
Some of the functions in test cases escape output and make the results of the test case contains those output this need to be fix so the framework doesn`t encounter issues when getting test case result 
Test Result #
```
Test Run On           : 02/24/2019 17:16:53
Test Category         : Functional
Test Area             : BACKUP
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:18
[hyperv] …
```
> Hyperv : Fixed test cases escaped outputs 

- Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
- Testscripts/Windows/DM-MAXMEMHONOR.ps1
- Testscripts/Windows/DM-MINMEMHONOR.ps1
- Testscripts/Windows/DM_HIGH-PRIORITY.ps1
- XML/TestCases/FunctionalTests-DynamicMemory.xml
Issue:
Some of the test cases failed due to variable issues during the run ( no getting the expected values) 
Verification tests : 
```
Test Run On           : 02/28/2019 12:29:55
Test Category         : Functional
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:30
1 DYNAMIC-MEMORY-HIGH-PRIORITY                                                   PASS                27.28
Test Run On           : 03/01/2019 …
```
> Hyperv : Fix DM testcase issues

- Libraries/Database.psm1
- TestControllers/TestController.psm1
> Fix: Duplicate function Upload-TestResultToDatabase

- Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
Fix test cases BVT-VERIFY-UUID-FSTAB against SLES12.3 and SLES12.4
> BVT-VERIFY-UUID-FSTAB: fix for SLES12

- TestProviders/OLVMProvider.psm1
This commit fixes to invoke DeployVM with OL specific credentials
Issue # 
---
> OL: Fix for correct user in OLVM deployment

- Libraries/Azure.psm1
The code changes to use template for OLVM deployment. 
---
> OL: Enhancement to use template for OLVM deployment

- TestProviders/OLQProvider.psm1
Issue logs: 
```
03/05/2019 10:18:55 : [INFO ] Validating XML Files from C:\GitHub\LISAv2 folder recursively...
03/05/2019 10:19:04 : [INFO ] Collected Test : BVT-VERIFY-DEPLOYMENT-PROVISION
03/05/2019 10:19:04 : [INFO ] 1 Test Cases have been collected
03/05/2019 10:19:04 : [INFO ] Starting the test
03/05/2019 10:19:04 : [INFO ] BVT-VERIFY-DEPLOYMENT-PROVISION started running.
03/05/2019 10:19:04 : [ERROR] EXCEPTION: Cannot find an overload for "DeployVMs" and the argument count: "6".
03/05/2019 10:19:04 : [ERROR] Source: Line 40 in script .\TestProviders\OLQProvider.psm1.
03/05/2019 10:19:04 : [INFO ] LISAv2 exit code: 1
```
---
> OLQ: Fixed missing parameter in DeployVM function

- README.md
Add secret file sample and usage, provide guideline for users which want to user their own subscription.
---
> Add secret file sample and usage.

- Testscripts/Linux/CORE-InitrdModulesCheck.sh
- Testscripts/Linux/LSVMBUS.sh
- Testscripts/Linux/NUMA_check.sh
- Testscripts/Linux/timesync_config.sh
- Testscripts/Linux/utils.sh
On `-TestCategory "Functional" -TestArea "CORE"` the following tests have failed due to unmet prerequisites:
LSVMBUS
INITRD-MODULES-CHECK
CHECK-NUMA
CHECK-NUMA-MAXIMUM
TIMESYNC-BASIC
This this fixes the installation of their prerequisites and cleans up the code by using the `Testscript\Linux\utils.sh` library `function install_package ()` which already differentiates between distros.
Issue #
> Fix install requirements in core functionality test scripts

- Libraries/Azure.psm1
Until now, if -UseExistingRG was set, the framework would not check if the existing RG had a lock on it. As a result, the function Delete-ResourceGroup would enter an infinite loop. Added a check for lock, and if any lock is set on the VM, the RG cleanup will be skipped and a warn would show up in the logs. 
- Also added RG cleanup becasue it was missing. Only the resources inside the RG were cleaned with the old code.
.............
03/06/2019 12:35:20 : [ERROR] Failed to delete resource PrimaryNIC-LISAv2-OneVM-ubuntuAz-SC48-20190227112013-role-0. We will try to remove it in next attempt.
03/06/2019 12:35:20 : [INFO ] Removing resource PublicIPv4-89767, type Microsoft.Network/publicIPAddresses
03/06/2019 12:35:20 : [ERROR] Failed to delete resource PublicIPv4-89767. We will try to remove …
> Azure: Delete-ResourceGroup lock fix
