RunTests.ps1
Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
XML/TestCases/StressTests.xml

1. Added azure reboot stress test
2. Fixed xml save failure when a relative path is given as a parameter, for the following scripts:
RunTests.ps1
UpdateGlobalConfigurationFromXmlSecrets.ps1

Added reboot azure stress test and fixed scripts

---

RunTests.ps1

Can not removal all global variables in live session, so it won't clear variables successfully. It shows other distro name in run-time log.  New fix tested in the same PS console, and verified no log string like "Distro Already Detected as : xxxxx"

Removal-Variable exception in final block

---

Libraries/Framework.psm1
RunTests.ps1
UnitTests/PowerShell/Libraries.Azure.Tests.ps1
UnitTests/PowerShell/Libraries.CommonFunctions.Tests.ps1
UnitTests/PowerShell/Libraries.ExtensionLibrary.Tests.ps1
UnitTests/PowerShell/Libraries.Framework.Tests.ps1
UnitTests/PowerShell/Libraries.HyperV.Tests.ps1
UnitTests/PowerShell/Libraries.Test-Framework.Tests.ps1
UnitTests/PowerShell/Readme.md

ARMImageName parameter value may come with leading spaces,
which leads to errors in the ARM templates.
This patch makes sure that the ARMImageName value is properly
trimmed before any usage.

azure: Trim ARMImageName value before usage and added unit simple tests to partially test the affected code

---

Testscripts/Linux/run-ntttcp-and-tcping.sh

Saved from last feedback. (The file was not saved in previous check-in)
"|| return" after "cd" command will act successful return to caller if "cd" cmd fails

two lines missing in last check-in

---

Libraries/Framework.psm1

Fixed the flow for customKernel case

---

Libraries/Framework.psm1

The fix applied in PR#125 is wrong. 
It just hides the problem instead of fixing it. The bug is caused by the empty string in $ARMImageName. 
To resolve this issue, we need to add one more condition to if statement to check if $ARMImageName is empty string.
The new PR is created with correct fix.
PR execution has been verified.

Correcting PR#125

---

Testscripts/Linux/perf_fio.sh
Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
XML/TestCases/PerformanceTests.xml

1. Binaries are moved to Microsoft designated storage account - partnerpipelineshare.
2. **[Urgent]** Fixed broken perf_fio.sh in LISAv2 master branch.

Fixed non Microsoft blob access for FIO test

---

Testscripts/Windows/PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
XML/TestCases/PerformanceTests.xml

* [Fix] Two support files for NTTTCP tests were not being uploaded. Added them to XML definition.
* [Refactoring] Moved hardcoded linux script names from Powershell to XML definition.

Fixed broken ntttcp test

---

Testscripts/Linux/customLISInstall.sh

As discussed in the team, we are moving kernel-devel rpms to designated Microsoft storage account.

Fixed non Microsoft blob access for kernel-devel rpms

---

Libraries/CommonFunctions.psm1

Some distros were failing to execute `dmesg` in the absense of sudo permissions.
Fixed with -RunAsSudo

Fixed issue of collecting VM logs

---

XML/VMConfigurations/PerformanceTestsConfigurations.xml

Standard_DS14 size is being deprecated from lot of regions now.
This is resulting in test failure.

Updated the FIO VM size to Standard_DS14_v2

---

Testscripts/Linux/Linux-Test-Project-Tests.sh

Copied the LTP result to "TestExecution.log" file which is by default downloaded by LISAv2 framework.

Fixed issue of LTP complete results are not being downloaded

---

Libraries/CommonFunctions.psm1

Bad commit:
https://github.com/LIS/LISAv2/commit/d6fd2dbdac0d768bb582ce32e9ddd95136aabca6
LIS-LogCollector.sh was renamed to CORE-LogCollector.sh but the references were not modified.

Fixing the issue introduced in PR#168

---

Libraries/CommonFunctions.psm1

A small typo was introduced in my last PR which is causing the warning. Fixed it.

Typo fix in WrapperCommandsToFile

---

Testscripts/Linux/Linux-Test-Project-Tests.sh
XML/Other/ReplaceableTestParameters.xml
XML/TestCases/CommunityTests.xml

Now, LTP tests can also be executed against any "git tag" using -CustomParameters feature.

LTP tests updated to use latest release version

---

Documents/How-to-use.md

Keep the suggestion for bash and python while we keep the PS in Verb-Entity format.

Corrected function name format suggestion

---

AzureTestSuite.ps1
Libraries/CommonFunctions.psm1

Test summary now has following changes -
1. Header line
2. Sr. no. for each test case
3. Execution time is mentioned same line with test result (as requested by Simon)

Combined test result and execution time in one line

---

Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
Testscripts/Windows/SETUP-NET-Add-Max-NIC.ps1
Testscripts/Windows/SETUP-NET-Add-NIC.ps1
Testscripts/Windows/SETUP-NET-Switch-NIC.ps1

PR208 introduced a change that makes the use of
$xmlConfig.config.Hyperv.Host.ServerName deprecated. It has been
replaced with $xmlConfig.config.Hyperv.Hosts.ChildNodes[0].ServerName

fix: Changed hvServer as required by PR208

---

Testscripts/Linux/KDUMP-Config.sh
Testscripts/Linux/utils.sh
Testscripts/Linux/verify_vmbus_interrupts.sh
Testscripts/Linux/verify_vmbus_protocol_version.sh
Testscripts/Windows/Check-VMBusPanicEvent.ps1
XML/TestCases/FunctionalTests.xml
XML/VMConfigurations/FunctionalTestsConfigurations.xml

Added 4 VMBUS tests:
1. VMBUS_VERIFY_PROTOCOL_VERSION (checks vmbus info appears in dmesg)
2. VMBUS_VERIFY_INTERRUPTS (checks vmbus interrupts for each cpu)
3. VMBUS_PANIC_NOTIFIER (checks panic event sent to hypervisor)
4. VMBUS_PANIC_NOTIFIER_KDUMP (checks panic event sent to hypervisor when kdump is enabled)
tested on centos 7.5 and ubuntu bionic.
VHD under test F:\Hyper-V\VHDs\lisav2\Centos_7.5_x64.vhd
Total Executed TestCases        2 (       2 Pass,        0 Fail,        0 Abort)
Total Execution Time(dd:hh:mm) 0:0:8
1. VMBUS_PANIC_NOTIFIER : PASS : 3.73
2. VMBUS_PANIC_NOTIFIER_KDUMP : PASS : 4.95
VHD under test …

hyperv: Added VMBus tests

---

Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1

This helps to isolate the capture VHDs based on build numbers and build names.
Note: This change is required for migration to LISAv2 for existing pipelines.

Appending BUILD NUMBER/NAME to captured VHD

---

RunTests.ps1

As RGIdentifier is required for both hyperv & azure move it to proper place to avoid confusion for new users.

Move RGIdentifier to required for both hyperv & azure

---

Libraries/HyperV.psm1

On VM creation 20 retries is too low (20*5 seconds). Increasing to 50
retries because sometimes a VM will take longer to boot

hyper-v: Increase retry count on getting IP

---

Testscripts/Linux/enableRoot.sh

This fixes an issue where the ssh daemon config file could remain blank after the changes.
Adding a sync command to flush all the changes to disk.

enableRoot: Do sync to fix #244

---

AzureTestSuite.ps1

Variable VmSetup is only defined for HyperV but it is used irrespective of Test Platform which is causing referring to null array when running Azure Test cases.

Fixed a breaking issue introduced in PR #238

---

Libraries/CommonFunctions.psm1
Testscripts/Linux/customKernelInstall.sh

This patch allows multiple kernel files to be installed -- for example hyperv daemons, image or debug kernel.
Example Run-Lisav2 argument:
-CustomKernel "localfile:C:\debfolders\*.deb". Now lisav2 will make sure it uploads all the files and installs them.
Works with -CustomKernel "localfile:C:\debfolders\*.rpm" too.

kernel_install: Added support for multiple kernel install files

---

JenkinsPipelines/Scripts/InspectVHD.ps1
Libraries/CommonFunctions.psm1

**Fixes the issue of incorrect filename when SAS URL is given for download.**
**For example:** 
**SAS URL:** https://xxxxxxxxxxxxxxxx.blob.core.windows.net/vm-images/SLES15-Azure.x86_64-1.0.99-Build2.24.vhd?sp=r&st=2018-10-18T00:00:00Z&se=2018-10-28T00:00:00Z&spr=https&sv=2017-11-09&sig=xXxXxXxXxXxXxXxXxXxXxXxXxX&sr=b 
**Downloaded filename:**  SLES15-Azure.x86_64-1.0.99-Build2.24.vhd?sp=r&st=2018-10-18T00:00:00Z&se=2018-10-28T00:00:00Z&spr=https&sv=2017-11-09&sig=xXxXxXxXxXxXxXxXxXxXxXxXxX&sr=b'
**Expected filename:**  SLES15-Azure.x86_64-1.0.99-Build2.24.vhd

Fixed issue in SAS URL file name (Inspect-VHD.ps1)

---

Testscripts/Linux/utils.sh

I'm running the tests with non root user ( a sudo user). 
In this case I see that test files are copied to /home/$username not to /root
However when scripts are run on guest as sudo user the $HOME will be /root and files are not there in /root

utils.sh: Set LIS_HOME to location where files copied to

---

Libraries/Azure.psm1
XML/TestCases/SmokeTests.xml

Now, you can deploy VMs with ephemeral OS disk using following xml tag :
```
<AdditionalHWConfig>
<DiskType>Managed</DiskType>
<OSDiskType>Ephemeral</OSDiskType>
</AdditionalHWConfig>
```
Note, You can not use Unmanaged disk + Ephemeral disk configuration.
Validations needed -
**Using default image (ARMImage)**
**Using custom VHD (Captured Image)**

Azure: Added support to ephemeral OS Disk (Preview)

---

Run-LisaV2.ps1

When lisav2 workspace is changed there is no need to have all the .git files copied plus a lot of temp files from previous runs, which can linearly increase the times for lisav2 to run, without manual cleanup.
PR tested internally and works fine.

lisav2: Don't copy temp files on workspace change

---

JenkinsPipelines/Run-Boot-Stress-Tests.groovy
JenkinsPipelines/Run-Linux-Tests.groovy
Libraries/Framework.psm1
Run-LisaV2.ps1

Removed all references to the following two switches:
-UpdateGlobalConfigurationFromSecretsFile
-UpdateXMLStringsFromSecretsFile
When the XMLSecrets file is present, we will execute as if these parameters were both true.  This means we will also generate an error if the file is present and the flags were intended to be omitted.  In looking at the groovy execution, we used both flags each time.  This may be different in job definitions.

Removed Obsolete SecretsFile Switches 

---

Testscripts/Linux/customKernelInstall.sh

hyperv-tools contains the lsvmbus tool, removing package so we can install the new version

customKernelInstall: Remove hyperv-tools on rhel

---

Libraries/CommonFunctions.psm1
Libraries/Framework.psm1

Reverts LIS/LISAv2#349
@juhlee-microsoft I have found that there is one more commit that got merged which wasn t tested, i ll revert it for now

Revert "azure: ARMImageName param can be empty when OSVhd is set"

---

Testscripts/Linux/azuremodules.py

os.path.isfile can't run against file name with wildcard
Run against clearos and centos, both are pass

azuremodules.py: Fix issue in distro detection

---

Libraries/Framework-Azure.psm1

This is fixing an issue on Azure where lisav2 would fail if -OsVHD param was given. The framework is working with either OsVHD or ARMImageName param. But in Framework-Azure.psm1 no check was made to see what parameter is available and what parameter isn't. This is adding an extra check before manipulating each of these params.
Even though the error message doesn't explicitly throw a message regarding the params issue, L33 which is pointed in Framework-Azure.psm1 is the one that triggers this.
11/08/2018 13:23:58 : [INFO ] Created LogDir: .\TestResults\2018-08-11-05-23-58-0449
11/08/2018 13:23:58 : [INFO ] -VMGeneration not specified. Using default VMGeneration = 1
.\Run-LisaV2.ps1 -TestLocation 'westus2' -RGIdentifier 'adsuhoTest' -TestPlatform 'Azure' -TestNames …

framework: $OsVHD/$ARMImageName parameter bugfix

---

Testscripts/Linux/SR-IOV-Utils.sh

Fixed VerifyVF function. VF name wasn't properly set in some cases on Azure. Since on Azure we have an IP set before the test starts, we now look for the IP to get the synthetic nic. With the synthethic NIC we can further get the VF .
Thu Nov 08 14:46:18 2018 : Testscript running on suse_15
Thu Nov 08 14:46:18 2018 : Successfully initialized testscript!
Thu Nov 08 11:46:18 2018 : VF device,  , was not found!
Thu Nov 08 11:46:18 2018 : VF device,  , was not found!
**As you can see, the VF name is empty**
Thu Nov 08 14:48:56 2018 : Testscript running on suse_15
Thu Nov 08 14:48:56 2018 : Successfully initialized testscript!
Thu Nov 08 14:48:56 2018 : VF is in use
(PS log)
11/08/2018 14:49:10 : [INFO ] CURRENT - **PASS    - 1** 11/08/2018 14:49:10 : [INFO ] CURRENT - FAIL    - 0
11/08/2018 …

SR-IOV-Utils.sh: Function fix for SLES15

---

Libraries/Framework-Azure.psm1

Right now lisav2 doesn't accept multiple test areas at runtime (e.g. we can't run KVP,FCOPY,etc at once). We can only run a full category or a single area. This commit is giving some flexibility since we can control better what tests we want to run.
**This is not changing previous runtime parameters/behavior (e.g. one area testing will work as well), just adds a small improvement.** 
PS C:\Users\v-adsuho\Documents\lisav2> .\Run-LisaV2.ps1 -TestPlatform 'Azure' -ARMImageName 'Canonical UbuntuServer 14.04.5-LTS latest
' -RGIdentifier 'adsuhoTest' -TestLocation 'westus2' -TestCategory 'Functional' **-TestArea 'KVP,CORE,SRIOV'**
11/08/2018 13:49:21 : [INFO ] Created LogDir: .\TestResults\2018-08-11-05-49-21-2079
11/08/2018 13:49:21 : [INFO ] Test parameters have been validated successfully. …

framework: Multiple test areas at runtime

---

XML/TestCases/FunctionalTests-SRIOV.xml
XML/TestCases/FunctionalTests.xml

FunctionalTests.xml contained tests with wrong categories/areas/tags:
--Runtime_Memory_Resize TCs had "Stress" category - It should be "Functional". Changed Area from Runtime_Memory_Resize to RUNTIME_MEMORY. Changed tag from runtime_memory to memory (to match Dynamic Memory test cases).
--FCOPY TCs had "FCOPY" category - it should be "Functional"
--Network tests had "NET" area and tags - it should be "NETWORK"
--Uppercase area for dynamic memory TCs
--Added network tag to VERIFY-SRIOV-LSPCI TC.

FunctionalTests.xml: Refresh category/area/tags

---

Testscripts/Linux/BVT-VERIFY-BOOT-ERROR-WARNINGS.py

Issue #26 : Improve checking of the call traces
Current method: dmesg | grep -i 'call trace'
Proposed method : grep -rnw '/var/log' -e 'call trace' --ignore-case
Before fix :
ARM Image under test Canonical : UbuntuServer : 18.04-LTS : latest
Total Executed TestCases         1 (        0 Pass,         1 Fail,         0 Abort)
Total Execution Time(dd:hh:mm) 0:0:3
1. BVT-VERIFY-BOOT-ERROR-WARNINGS : FAIL : 3.42
Logs : 
11/13/2018 03:07:22 PM : INFO : Checking for ERROR and WARNING messages in  kernel boot line.
11/13/2018 03:07:22 PM : DEBUG : [    4.661236] GPT: Use GNU Parted to correct GPT errors.
[    4.983814] RAS: Correctable Errors collector …

Fixing issue #26 

---

Testscripts/Linux/customKernelInstall.sh

Added "export DEBIAN_FRONTEND=noninteractive" for Ubuntu latest, proposed, proposed-azure and
proposed-edge. Without it, install may fail because of unnecessary
prompts showing while installing the new kernel.

customKernelInstall.sh: Fix for PR 357

---

Libraries/HyperV.psm1
XML/AzureVMSizeToHyperVMapping.xml

This change is needed not to use too much RAM on HyperV tests when executing BVT tests.

hyperv: lower RAM for Standard_DS4_v2 flavor to 8192 MB

---

Libraries/CommonFunctions.psm1

The current log file should be the initial log file, not the final log file.
This PR fixes the bad implementation.

kernel_logs: fix initial log file

---

Libraries/CommonFunctions.psm1

This patch fixes a code regression added in https://github.com/LIS/LISAv2/pull/411
Execution tested on Ubuntu 16.04
```
11/21/2018 20:34:00 : [INFO ] Checking for call traces in kernel logs..
11/21/2018 20:34:00 : [INFO ] No kernel call traces found.
11/21/2018 20:34:00 : [INFO ] ** Initial and Final Kernel Logs have same content **
...
11/21/2018 20:34:09 : [INFO ] CleanUP Successful for ICA-HG-SingleVM-test-NVCX75226-636784363391..
11/21/2018 20:34:09 : [INFO ] ~~~~~~~~~~~~~~~TEST END : SQM-BASIC~~~~~~~~~~
11/21/2018 20:34:09 : [INFO ] CURRENT - PASS    - 1
11/21/2018 20:34:09 : [INFO ] CURRENT - FAIL    - 0
11/21/2018 20:34:09 : [INFO ] CURRENT - ABORTED - 0
```

kernel_logs: added error log and fix regression

---

JenkinsPipelines/Scripts/InspectVHD.ps1
JenkinsPipelines/Scripts/ReceivePartnerFiles.ps1

PR #402 changed the way log filename is handled.
However, the Jenkinspipeline/Scripts are ran outside of Run-LisaV2.ps1 which now handles the log filename, so these were failing.
This has been tested internally and it fixed the launcher and test execution jobs.

penguinator: fix LogFileName in scripts

---

Libraries/Framework-Azure.psm1
Libraries/XmlProcessing.psm1
Run-LisaV2.ps1

1 Fix the bug of update the value of TestCategory,TestArea,TestNames and TestTag failed
2 Add a parameter TestPriority, when it is enabled, cases exact equal priorities will be run

Add a parameter TestPriority, to enable run test by priority

---

Utilities/AddAzureRmAccountFromSecretsFile.ps1
Utilities/AnalyseAllResults.ps1
Utilities/CopyVHDtoOtherStorageAccount.ps1
Utilities/Get-AzureVMs.ps1
Utilities/Get-SubscriptionUsage.ps1
Utilities/Get-SubscriptionUsageTopVMs.ps1
Utilities/ManageTestStorageAccounts.ps1
Utilities/UploadVHDtoAzureStorage.ps1

If main run-lisav2 script will call these scripts, it will conflict in using the $LogFileName variable.
This is to fix that behavior if the scripts are ran independently of lisav2

Fix issue #452

---

XML/TestCases/FunctionalTests-SRIOV.xml
XML/TestCases/StressTests.xml
XML/VMConfigurations/SmokeTestsConfigurations.xml

Introduced a bug with https://github.com/LIS/LISAv2/pull/462
This is fixing the issue of naming starting with a number - 1VM8NIC was
changed to OneVM8NIC

Fix for SetupTypeName

---

Testscripts/Windows/SETUP-SR-IOV-Configure.ps1

Changed deprecated function name RunLinuxCmd to Run-LinuxCmd in SETUP-SR-IOV-Configure.ps1

hyperv: Fix for SR-IOV setupscript

---

Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
XML/Other/ReplaceableTestParameters.xml
XML/TestCases/PerformanceTests.xml

To compare the results for the performance testing, we need a framework that:
- is generic - should work for all performance results
- has machine readable output
For genericity, all performance test cases should have a JSON output, with the name 
> TestCaseName_perf_results.json
The JSON file should contain an array of objects, with the object having the following structure
{
"Id": ValueID,
"ResultType1": Value1,
"ResultType2": Value2,
"ResultType3": Value3
}
Is mandatory to have at least the Id field.
This has to be implemented for all performance test cases to be able to have a comparison of the results.
If the test does not implement, there will be no result comparison possible.
The changes in the other test cases should require refactoring and adding this feature.
This feature is …

perf_framework: iperf3: output perf results in a generic way 

---

Testscripts/Linux/perf_fio.sh

The storage bash scripts require arrays to be defined as:
'val1 val2'
and not:
(val1 val2)
This patch fixes perf_fio.sh to manage arrays given as (val1 val2)

stor_perf: fix backwards compatibility in params

---

Run-LisaV2.ps1

This patch fixes the azure secrets load failure.
Without this patch, lisav2 fails with error:
> [azure] Select-AzureRmSubscription : Please provide a valid tenant or a
> valid
> [azure] subscription.
> [azure] At C:\LISAv2\FGNS14927\AutomationManager.ps1:417 char:27
> [azure] + ... scription = Select-AzureRmSubscription -SubscriptionId
> $AzureSetup.Su ...
> [azure] 
> [azure]     + CategoryInfo          : CloseError: (:)
> [Set-AzureRmContext], ArgumentEx
> [azure]    ception
> [azure]     + FullyQualifiedErrorId :
> Microsoft.Azure.Commands.Profile.SetAzureRMConte
> [azure]    xtCommand
> 
> 
The problem was introduced by commit:
https://github.com/LIS/LISAv2/commit/087bfca718cc72d5d9a27790d7f71c6e35b5255d

lisav2: fix azure secrets load

---

AutomationManager.ps1

$testSummary wasn't initialized when a test exception occured. This meant that a previously set $testSummary variable was passed to an aborted test. This fixes https://github.com/LIS/LISAv2/issues/523 
- Moved $testSummary & $testResult var init outside the try-catch block
ARM Image Under Test  : Canonical : UbuntuServer : 18.10 : latest
Total Test Cases      : 36 (21 Pass, 0 Fail, 15 Abort)
Total Time (dd:hh:mm) : 0:4:11
1 BVT-VERIFY-DEPLOYMENT-PROVISION                                    PASS                 7.63 
FirstBoot : PASS 
FirstBoot : …

lisav2: initialize $testSummary for every test run

---

Libraries/Azure.psm1

Added Location param to  Get-AzureRmStorageUsage command-let inorder to remove below warning
[INFO ] Estimating storage account usage...
WARNING: Get global storage usage is obsolete, please use get location usage
with -Location Parameter instead.
Test Run On           : 12/17/2018 12:22:10
ARM Image Under Test  : OpenLogic : CentOS : 7.5 : 7.5.20180815
Total Time (dd:hh:mm) : 0:0:13
ID TestCaseName                                                 TestResult TestDuration(in minutes)
1 BVT-ROOT-DEVICE-TIMEOUT-CHECK …

Added Location param to Get-AzureRmStorageUsage

---

Libraries/LISAV2-Framework.psm1

This commit allows specifying multiple test categories, instead of none or only one.

lisav2: allow multiple test categories, comma separated

---

Testscripts/Linux/CreateRaid.sh
Testscripts/Linux/perf_fio_nfs.sh
Testscripts/Linux/utils.sh

Removed hardcoded commands and packages names from script.
For rhel, firewall config is also required.
Tested on:
- Ubuntu 16.04
- Centos 7.5
- RHEL 7.6
- SLES 12 SP2
- SLES 15
Fixed issue https://github.com/LIS/LISAv2/issues/461

perf: fix nfs installation for rhel/centos/sles

---

Testscripts/Linux/perf_fio.sh

Previously this would thrown an error as below, given that -f does not work with globs.
"bash: [: /etc/lsb-release: binary operator expected"

perf_fio.sh: fix release file detect condition

---

XML/Other/ignorable-boot-errors.xml

Adressing issue #516 
**Before fix :** 
Output : 
01/03/2019 08:56:36 AM : INFO : Checking for ERROR and WARNING messages in  kernel boot line.
01/03/2019 08:56:36 AM : DEBUG : 713:Jan  3 08:55:44 LISAv2-OneVM-staginglisav2-LO91-20190103085323-role-0 HV_FCOPY: open /dev/vmbus/hv_fcopy failed; error: 2 No such file or directory
825:Jan  3 08:55:47 LISAv2-OneVM-staginglisav2-LO91-20190103085323-role-0 snapd[1355]: 2019/01/03 08:55:47.971567 helpers.go:119: error trying to compare the snap system key: system-key missing on disk
910:Jan  3 08:55:58 LISAv2-OneVM-staginglisav2-LO91-20190103085323-role-0 systemd-resolved[930]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
911:Jan  3 08:55:58 …

Add ignorable boot errors and warnings for ubuntu 18.04 on Azure

---

Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
XML/TestCases/FunctionalTests-SRIOV.xml
XML/TestCases/StressTests.xml

STRESSTEST-VERIFY-RESTART-MAX-SRIOV-NICS current it didn't go into STRESSTEST-VERIFY-RESTART.ps1 because our framework start from testScript.
Remove PowershellScript section from VERIFY-IFUP-NICS-SRIOV, this file (VERIFY-TEST-SCRIPT-IN-LINUX-GUEST.ps1) doesn't exist.
Test results
Test Run On           : 01/09/2019 05:15:48
ARM Image Under Test  : canonical : ubuntuserver : 18.04-lts : Latest
Total Test Cases      : 2 (2 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:17
1 VERIFY-IFUP-NICS-SRIOV …

Replace PowershellScript with testScript as init script for test cases

---

Utilities/Clean-OldHypervVMs.ps1

Lisav2HyperVCleanup.ps1 will be used for Hyper-V VM cleanup. The current
cleanup process will be performed this way:
- If the VM is running for more than 48 hours, it will be stopped
- If the VM was created 5 days or earlier, it will be removed (VM files
and VHD files)
The script will also look for empty VM groups and delete them.
To run it, you need to call it with a parameter of the hostname that
will be cleaned.
e.g. .\Lisav2HyperVCleanup -HvServer "server_to_be_cleaned"
This is the solution for https://github.com/LIS/LISAv2/issues/439

utilities: Added PS script for Hyper-V VM cleanup

---

XML/TestCases/FunctionalTests-DynamicMemory.xml

Added missing utils.sh
Before fix error : 
[ERROR] Background Process terminated from Linux side with error code :  1
[ERROR] [sudo] password for lisa: /bin/bash: utils.sh: No such file or directory AZURE-LINUX-EXIT-CODE-1
Verification test : 
Test Run On           : 01/11/2019 16:47:44
VHD Under Test        : Ubuntu_18.04.1.vhdx
Test Category         : Functional
Total Time (dd:hh:mm) : 0:0:18
1 DYNAMIC-MEMORY-START-HIGH-COMPETE …

Fix DYNAMIC-MEMORY-START-HIGH-COMPETE

---

Testscripts/Linux/SRIOV-VerifyVF-Connection.sh

asterisk removed from 'find' commands. In some cases, it returned more
interfaces than expected.

SRIOV-VerifyVF-Connection.sh: small fix

---

Libraries/Azure.psm1
TestControllers/AzureController.psm1
UnitTests/PowerShell/TestControllers/AzureController.Tests.ps1
Utilities/AddAzureRmAccountFromSecretsFile.ps1

This PR adds Azure Controller unit tests and moves the Utilities/AddAzureRmAccountFromSecretsFile.ps1 logic to Libraries/Azure.psm1 so that it can be properly tested.

unit_tests: added azure controller unit tests

---

Libraries/IntegrationServiceLibrary.psm1
Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1

During run BVT-NET-IFUP-IFDOWN, the IP will change. 
Before fix, the collect log will still against the old ip.
01/15/2019 07:10:29 : [INFO ] Collecting LISAv2-OneVM-upstreamk-GK24-636831035060-role-0 VM Kernel Final Logs...
01/15/2019 07:10:29 : [INFO ] dos2unix: converting file E:\lili\upstream\Test\TestResults\2019-14-01-22-58-23-7452\BVT-NET-IFUP-IFDOWN\runtest.sh to Unix format...
01/15/2019 07:10:29 : [INFO ] Uploading E:\lili\upstream\Test\TestResults\2019-14-01-22-58-23-7452\BVT-NET-IFUP-IFDOWN\runtest.sh to lisa : 10.156.76.66, port 22 using Password authentication
01/15/2019 07:10:51 : [WARN ] Error in upload, Attempt 1. Retrying for upload
0
...
01/15/2019 07:15:42 : [INFO ] Calling function - Copy-RemoteFiles. Error in upload after 11 Attempt,Hence giving up
01/15/2019 …

hyperv: update IP in allVmData in case it has changed after reboot

---

Libraries/CommonFunctions.psm1
Libraries/TestLogs.psm1

Do not show all kernel logs in lisav2 output, as it makes the reading of the logs very hard.
Also sanitize the distro name in case unwanted output like "sudo: unable to resolve host" appears.
Partially fixes: https://github.com/LIS/LISAv2/issues/590
Execution tested:
```
Test Run On           : 01/16/2019 19:39:10
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-DAILY-LTS : latest
Total Time (dd:hh:mm) : 0:0:5
1 BVT-CORE-VERIFY-LIS-MODULES                                                       PASS …
```

log: do not show non error/warning kernel logs in the lisav2 output

---

Libraries/Azure.psm1

The framework didn't put InternalIP correctly. In case we had multiple VMs (over 10), then the 'imatch' would match VMs with double digits (e.g. client-10, client-11,) with the single digits one (e.g. with
client-1). That is breaking AllVMData since the Private IPs that are put there are not matching the VMs.
This is solving https://github.com/LIS/LISAv2/issues/613.
Since it's a framework change, **do not rush to merge** it until we have an approval for every requested reviewer.

framework: Wrong InternalIP in $AllVMData

---

XML/TestCases/FunctionalTests.xml

Using a larger crashkernel size is required for newer kernels, azure kernel or upstream take much more memory during crash.
Hyper-V :
Total Time (dd:hh:mm) : 0:0:8
1 KDUMP-CRASH-NMI                                                                   PASS                 6.24 
Azure : 
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Test Cases      : 2 (2 Pass, 0 Fail, 0 Abort)
Total Time (dd:hh:mm) : 0:0:9
ID TestCaseName …

kdump: increase crashkernel memory allocation

---

Libraries/IntegrationServiceLibrary.psm1
Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1

Addressing #626 
Verification Tests : 
01/22/2019 17:48:22 : [INFO ] SSH connection returns : Connected
01/22/2019 17:48:22 : [INFO ] Successfully reloaded hv_netvsc for 25 times
Test Run On           : 01/22/2019 17:32:18
VHD Under Test      :ubuntu_18.04.1.vhdx
Total Time (dd:hh:mm) : 0:0:16
1 STRESSTEST-CHANGE-MTU-RELOAD-NETVSC                                               PASS                14.42 
01/22/2019 18:29:40 : [INFO ] SSH connection returns : Connected
01/22/2019 …

Fix STRESSTEST-CHANGE-MTU-RELOAD-NETVSC

---

XML/AzureVMSizeToHyperVMapping.xml

Reduced the amount of vCPUs & memory in AzureVMSizeToHYperVMapping.xml.
Some of these mappings caused Hyper-V tests to fail because of large amount of requested resources (e.g. 200gb memory in some cases). Reduced all the used VM sizes used in HV to 4/8 vCPUs and 4/8 GB of memory (depending on the TC).
This is solving https://github.com/LIS/LISAv2/issues/624

HyperV VM sizes: Updated memory/vCPU

---

Libraries/HyperV.psm1
TestControllers/TestController.psm1
TestProviders/HyperVProvider.psm1
TestProviders/TestProvider.psm1

hyperv: retry to remove snapshots on failure
hyperv: don't revert unneeded snasphots when the first test case is run, as it is not needed
Execution tested on HyperV:
```
1 BVT-CORE-VERIFY-LIS-MODULES                                                       PASS                 0.95
```

hyperv: don't apply checkpoints on the first run and retry to remove snaspshots

---

Libraries/Azure.psm1

HBS and HCS VM families were considered as H family until now and that was causing various issues in lisav2 testing.

azure: added HBC and HCS family support

---

Libraries/CommonFunctions.psm1
Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
Testscripts/Linux/NET-Max-NICs.sh
Testscripts/Linux/NET-Multicast.sh
Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
Testscripts/Linux/TestRDMA_MultiVM.sh
Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
Testscripts/Linux/nested_kvm_netperf_pps.sh
Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
Testscripts/Linux/nested_vm_utils.sh
Testscripts/Linux/restart-interface-reload-netvsc.sh
Testscripts/Linux/utils.sh
Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1
Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
XML/TestCases/FunctionalTests-Network.xml

ifconfig use is deprecated and newer distributions no longer include the package by default.
Replace ifconfig/ifdown/ifup commands with the new set of ip commands.
Rewrite VLAN interface create to not use interface config file, but rather only to current boot session.
*This model should be carried to further code refactor for configuring the secondary interfaces as well.*
Also rename testcase name and file "verify-ifdown-ifup-eth0-rmmod-modprobe-hv-netvsc.sh" to a shorter version.
---
Azure:
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
BVT-CORE-RELOAD-MODULES-SMP                                                       PASS                11.36 <- also pass on Hyper-V
VERIFY-RESTART-INTERFACE-RELOAD-NETVSC                                            PASS …

Replace deprecated ifconfig with iproute2 - ip commands

---

Testscripts/Windows/SETUP-STOR-TakeRevert-Snapshot.ps1
Testscripts/Windows/SRIOV-REBOOT-VM.ps1

Addressing #626
Test Run On           : 01/23/2019 17:31:31
VHD Under Test        : Centos_7.5_x64.vhdx
Total Time (dd:hh:mm) : 0:0:9
1 SRIOV-REBOOT-VM                                                                   PASS                 7.51 
Test Run On           : 01/23/2019 18:12:16
Total Time (dd:hh:mm) : 0:0:11
ID TestCaseName …

Fix functionality of Get-IPv4AndWaitForSSHStart in testcases

---

Testscripts/Linux/LIS-VERSION-CHECK.sh
XML/TestCases/BVT.xml

Build version is retrieved from modinfo and source version
is retrieved from lis-next hv_compat.h

LIS RPM: Add test to cross verify build version with source version

---

Testscripts/Windows/STRESS-Web.ps1

Addressing #593
Until further requirement to  support this test on other distributions, restrict it only to Debian/Ubuntu.
CentOS/Redhat will require epel repo setup to install nginx and further automation code.

STRESSTEST-WEB-PARALLEL-ACCESS: Restrict test only to Ubuntu/Debian

---

LISAv2-Framework.psm1
Libraries/HyperV.psm1
README.md
Run-LisaV2.ps1
TestControllers/HyperVController.psm1
XML/GlobalConfigurations.xml
XML/TestParameters.xml

SourceOsVHDPath parameter is not needed anymore, as now the OSVhd is already given in pipelines as a full path.
Previously to this patch, if SourceOSVhd existed, the full path of the lisav2 used vhd was the SourceOSVhd  + OsVhd.
Execution tested:
```
Test Run On           : 01/29/2019 16:09:59
VHD Under Test        : D:\diskimages\ubuntu-1810.vhdx
Total Time (dd:hh:mm) : 0:0:3
1 BVT-CORE-VERIFY-LIS-MODULES                                                       PASS …
```

lisav2: hyperv: remove SourceOsVHDPath parameter

---

Testscripts/Linux/nvme_blkdiscard.sh
Testscripts/Linux/nvme_fstrim.sh
Testscripts/Linux/utils.sh
XML/TestCases/FunctionalTests-NVME.xml

-nvme-fstrim testcase
-nvme-blkdiscard testcase
-updated timeout for all TCs ( Testcase might timeout before it`s done ) 
**Verification :** 
**Azure :**  
1NVME Drive :
```
Test Run On           : 01/30/2019 08:28:05
ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : latest
Total Time (dd:hh:mm) : 0:0:7
1 NVME-BLKDISCARD                                                                   PASS                  4.3 
Test Run On           : …
```

NVMe Direct: Add 2 new test-cases

---

Libraries/HyperV.psm1
TestControllers/TestController.psm1
TestProviders/HyperVProvider.psm1
TestProviders/TestProvider.psm1

The refactor removed snapshot usage on Hyper-V.
This patch brings back the snapshot feature usage in Hyper-V.
On HyperV platform, the VMs are reused for each test case that asks for the same VM setup type in order to decrease resource consumption.
General workflow (changes of this patch are in bold):
1. create vm
2. create checkpoint icabase for that vm
3. first test case is run on the vm
4. **if the first test case fails, create a checkpoint for the failed state.**
5. **apply icabase checkpoint**
6. second test case is run on the same vm, etc.
Fixes #599

hyperv: reuse failed test case vm

---

Testscripts/Linux/kernel_config_verify_test.sh
Testscripts/Windows/KERNEL-CONFIG-VERIFY-TEST.ps1
XML/Other/ReplaceableTestParameters.xml
XML/TestCases/FunctionalTests-OL.xml

This test compares the kernel configuration file with master.config stored in blob. 
The latest OL image have config file embedded so modified this PR to support it.

Add new test case for kernel config verify

---

Libraries/Azure.psm1

Sometimes, Azure throttles the requests. In this case, LISAv2 tries to
create resource group without any wait period. Which results in
successive failures, resulting in test Abort.
Adding wait period helps to bypass this issue.

Azure: wait 10s between resource group creation retry

---

TestControllers/TestController.psm1

Old junit testsuite : `LISAv2Test`
New junit testsute : `LISAv2Test-<TestPlatform>`
Old junit class : `Random Test ID`
New junit class : `<TestCategory>-<TestArea>`
This gives a clear picture when compiling results on jenkins.

Framework : Fixed junit report - testsuite name and class

---

Testscripts/Windows/Timesync-VDSO.ps1

Updated real time threshold from 5.0 to 10.0, since on Windows 2019 host, real time is about 7s, sometimes go to 9s.
Changes based on customer feedback in https://github.com/LIS/lis-test/pull/1152
Tests : 
```
Test Run On           : 02/06/2019 09:02:22
VHD Under Test        : Centos_7.5_x64.vhdx
Total Time (dd:hh:mm) : 0:0:3
1 TIMESYNC-VDSO                                                                     PASS                  1.7 
Test Run On …
```

TIMESYNC-VDSO: update real-time threshold values

---

Testscripts/Linux/DM_Top_Load_Average.sh
XML/TestCases/FunctionalTests-DynamicMemory.xml

This is a regression test based on upstream commit:
"Drivers: hv: Ballon: Make pressure posting thread sleep interruptibly"
Test steps:
1. Enable dynamic memory with Hyper-V manager.
2. Start the guest, check the top metrics after waiting for several minutes.
3. Check load average value of past minutes.
Tests : 
```
Test Run On           : 02/06/2019 17:21:08
Total Time (dd:hh:mm) : 0:0:10
1 DYNAMIC-MEMORY-TOP-LOAD-AVERAGE …
```

Add new DYNAMIC-MEMORY-TOP-LOAD-AVERAGE testcase

---

XML/TestCases/FunctionalTests.xml

```[LISAv2 Test Results Summary]
Test Run On           : 02/08/2019 09:32:23
ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : latest
Total Time (dd:hh:mm) : 0:0:4
1 VMBUS_VERIFY_INTERRUPTS                                                           PASS                 0.97 
```
Tested with 64 core VMSize (Standard_E64s_v3) : 
CPU core 0 is processing VMBUS interrupts.
CPU core 1 is processing VMBUS interrupts.
CPU core 2 is processing VMBUS interrupts.
CPU core 3 is processing VMBUS interrupts. …

Add VMBUS_VERIFY_INTERRUPTS to Azure platform

---

LISAv2-Framework.psm1
Libraries/CommonFunctions.psm1
Libraries/TestLogs.psm1
Run-LisaV2.ps1
TestControllers/TestController.psm1
Testscripts/Linux/build_gcov_kernel.sh
Testscripts/Linux/collect_gcov_data.sh
Testscripts/Linux/generate_gcov.sh
Testscripts/Linux/generate_gcov_report.sh
Testscripts/Windows/Build-GcovKernel.ps1
Testscripts/Windows/Get-GcovReport.ps1
Utilities/CodeCoverage/Upload-Report.ps1
Utilities/CodeCoverage/create_coverage_file.py
Utilities/Launch-GcovTest.ps1
XML/Other/ReplaceableTestParameters.xml
XML/TestCases/Other.xml

Changelog:
- Added new test (BUILD-GCOV-KERNEL) to build the kernel from source package with gcov support using custom config.
The test will create a folder "CodeCoverage\artifatcs" in LISA root directory where built packages will be stored.
- Added EnableCodeCoverage option in Run-LISAv2.ps1 that will enable gcov logs collect during the final kernel logs collect (per each test).
This needs to be used along with CustomKernel param (to have the kernel with gcov support installed).
Logs will be stored in "CodeCoverage\logs\${TestName}"
- Added new test (BUILD-GCOV-REPORT) to convert the logs into gcov files, then into html reports.
For now it only generates reports for the following files: hv_kvp.c, hv_fcopy.c, vmbus_drv.c
Supported base distro: Ubuntu

Code Coverage: Added code coverage feature

---

Libraries/CommonFunctions.psm1
Testscripts/Linux/customKernelInstall.sh

Introduced upstream-stable as a new custom kernel supported. This will pull the latest stable from kernel.org.
Simplified logic in checking valid kernel types.
---
**linux-next daily:**
[INFO ] Old kernel: 4.15.0-1037-azure
[INFO ] New kernel: 5.0.0-rc5-next-20190207
**upstream stable latest:**
ubuntu:
[INFO ] Old kernel: 4.15.0-1037-azure
[INFO ] New kernel: 4.20.7
redhat:
[INFO ] Old kernel: 3.10.0-862.11.6.el7.x86_64
[INFO ] New kernel: 4.20.7
**Expected failure:**
[ERROR] Only ppa proposed proposed-azure proposed-edge latest linuxnext netnext upstream-stable are supported. E.g. -CustomKernel linuxnext/netnext/proposed. 
Or use -CustomKernel <link to deb file>, -CustomKernel <link to rpm file>
[ERROR] Custom Kernel: liunxnext installation FAIL. Aborting tests.
[ERROR] Failed to set …

Framework: Upstream stable kernel support

---

Testscripts/Linux/customKernelInstall.sh

The new introduced check did not cover the rpm/deb packages cases, added a check for those too.
Tested with upstream pipeline:
[boot_test_small] 02/11/2019 09:46:18 : [INFO ] Old kernel: 3.10.0-862.11.6.el7.x86_64
[boot_test_small] 02/11/2019 09:46:18 : [INFO ] New kernel: 5.0.0-rc5-next-20190211-d4104460aec1

Fix for customKernelInstall.sh

---

Testscripts/Windows/AddVhdxHardDisk.ps1

An error might occur if the cmdlet is present, but the cluster service is not running, thus that method is not available.
Added additional check for the CSV path.

AddVhdxHardDisk.ps1: Addition fix for PR #725

---

Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1

Small refactor on how the result is checked during the bash script run.
This fixes https://github.com/LIS/LISAv2/issues/710
02/12/2019 11:13:14 : [INFO ] Test is still running!
02/12/2019 11:13:34 : [INFO ] Attempt number 22 to reach VM
[.........]
02/12/2019 11:13:37 : [INFO ] .\tools\plink.exe -t -pw ****** -P 22 lisa@*** "cat state.txt"
02/12/2019 11:13:39 : [INFO ] cat state.txt executed successfully in 1.18 seconds.
02/12/2019 11:13:39 : [INFO ] Test is still running!
02/12/2019 11:13:59 : [INFO ] Attempt number 23 to reach VM
[.........]
02/12/2019 11:14:02 : [INFO ] .\tools\plink.exe -t -pw ****** -P 22 lisa@***"cat state.txt"
02/12/2019 11:14:03 : [INFO ] cat state.txt executed successfully in 1.16 seconds.
02/12/2019 11:14:03 : [INFO ] Test is still running!
02/12/2019 11:14:23 : …

HyperV: Fix BVT-CORE-RELOAD-MODULES.ps1

---

Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1

Fixes #711 
Because of the refactor related to how test cases return the status results, the following tests need to be fixed in order to return proper statuses:
BVT-VERIFY-VHD-PREREQUISITES Test case script result does not match known ones:>>> PASS<<<
BVT-VERIFY-SSHD-CONFIG Test case script result does not match known ones:>>> PASS<<<
BVT-NET-IFUP-IFDOWN Test case script result does not match known ones:>>>2015<<<

Fix the value of the test case results

---

JenkinsPipelines/Run-Boot-Stress-Tests.groovy
LISAv2-Framework.psm1
Libraries/Azure.psm1
Libraries/CommonFunctions.psm1
Run-LisaV2.ps1
TestControllers/AzureController.psm1
TestControllers/TestController.psm1
Utilities/Launch-GcovTest.ps1
XML/Other/ReplaceableTestParameters.xml
XML/TestParameters.xml

Rename the current CustomParameters to CustomTestParameters, which is for overwriting the default parameter values defined in ReplaceableTestParameters.xml 
And enable CustomParameters for the parameters, the value format is the same as “Key1=Value1;Key2=Value2;…”, which can include TiPCluster=<ClusterId>;TipSession=<SessionId>; DiskType=Managed;Networking=SRIOV

Rename CustomParameters into CustomTestParameters, enable CustomParameters for the parameters.

---

TestControllers/TestController.psm1

If, 
```
$XMLSecrets = [xml] (Get-Content .\XML\AzureSecrets.xml)
$CurrentStorageXML = [xml](Get-Content .\XML\RegionAndStorageAccounts.xml)
```
then,
`$XMLSecrets.secrets.RegionAndStorageAccounts` should have all the child elements same as `$CurrentStorageXML.AllRegions`
.\XML\RegionAndStorageAccounts.xml will only be update if, XMLsecrets has `$XMLSecrets.secrets.RegionAndStorageAccounts` parent element.
Otherwise, RegionAndStorageAccounts.xml will be used, as is.

Azure: .\XML\RegionAndStorageAccounts.xml will be updated using secret file.

---

Documents/How-to-use.md
Libraries/TestLogs.psm1
Libraries/TestReport.psm1
TestControllers/TestController.psm1

In many ps1 test scripts, the old names used, to avoid change bunch of files to align new names, we choose to rename global ResultFailed/ResultPassed back to ResultFail/ResultPass.
Part fix for #763

Rename global ResultFailed/ResultPassed to ResultFail/ResultPass

---

XML/TestCases/FunctionalTests-DynamicMemory.xml
XML/TestCases/FunctionalTests-LiveMigration.xml
XML/TestCases/FunctionalTests-NVME.xml
XML/TestCases/FunctionalTests-OL.xml
XML/TestCases/NestedVmTests.xml
XML/TestCases/PerformanceTests.xml
XML/TestCases/StressTests.xml

Some Test areas are  in lowercase in xmls , they should be only uppercase in order to be uniform . 
Also some testcase names need the  test area in the name to be easier to identify what the test case covers (some need to be in more uniform state )

Cleanup testcase xmls

---

Testscripts/Windows/SETUP-SR-IOV-Configure.ps1

Also checked that "LogErr" is not present anywhere in LISAv2 powershell scripts.

Fix: Replaced LogErr with Write-LogErr in SETUP-SRI-IOV-Configure

---

TestControllers/TestController.psm1
XML/Other/ReplaceableTestParameters.xml

Fix: Replaceable test parameters can also replace test case names

---

Testscripts/Linux/SR-IOV-Utils.sh

We have found some issues with VF detection in cases where interfaces name went from eth10 onwards. With '\*', instead of one interface taken, the 'find' command would take eth1 but also eth10, eth11, etc. Removed '\*' to make sure only one interface is saved

SR-IOV-Utils.sh fix

---

Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
Testscripts/Windows/NET-HotAdd-MultiNIC.ps1
Testscripts/Windows/NET-HotAddRemove-Max-NIC.ps1

Network Gen2  test cases should return skipped on Gen1 VM

Fixed NET Gen2 testcases to return skipped instead of aborted

---

Libraries/HyperV.psm1

Until now, the hostname was only injected in /etc/hostname. In some cases, if the hostname present in /etc/hosts and /etc/hostname don't match, an error (sudo: unable to resolve host) will pop every time
commands are run in sudo in VM. This is breaking a few tests.
2/21/2019 08:24:59 : [INFO ] The interface that will be configured on LISAv2-TwoVM1Dep-ubuntuAzuretrusty-SX79-636863052186-dependency-vm is
sudo: unable to resolve host (none)
eth1
02/21/2019 10:40:48 : [INFO ] The interface that will be configured on LISAv2-TwoVM1Dep-ubAz-VG90-636863133854-dependency-vm is eth1

HyperV.psm1: Added the hostname in /etc/hosts

---

Libraries/TestHelpers.psm1

the Tools folder is used with lowercase, this created a problem when I checked-out the repository using WSL and Powershell was no longer able to resolve the path case insensitive

Replace usages of tools folder to be case sensitive in powershell files

---

Testscripts/Linux/NET-Copy-Large-File.sh
Testscripts/Linux/NET-Corruption.sh
Testscripts/Linux/NET-Max-NICs.sh
Testscripts/Linux/NET-Operstate.sh
Testscripts/Linux/NET-Test-Legacy.sh
Testscripts/Linux/NET-Test-Network.sh
Testscripts/Linux/NET-Test-Promiscuous.sh
Testscripts/Linux/NET-Verify-Boot-NoNIC.sh
Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
Testscripts/Linux/utils.sh
Testscripts/Windows/NET-File-Copy-SCP.ps1
Testscripts/Windows/NET-Test-Private-Network.ps1
Testscripts/Windows/SETUP-NET-Switch-NIC.ps1

Network tests had multiple fails on Hyper-V. This is fixing the
following:
- In Ubuntu 14.04, the 'ip link set dev INTERFACE up' doesn't work.
Added extra ifup check & ifup INTERFACE to consolidate this.
- Replaced Aborted with Skip state for Legacy and Max NICs tests if
tulip driver is not configured in kernel
- Fixed Switch Interface test cases. They only received the AllVMData
object, not a specific VMName to be set up.
- Enabled root for File Copy SCP.
- Various message fixes

NETWORK: Various fixes for Hyper-V

---

Libraries/HyperV.psm1

Automatic checkpoints are enabled by default Hyper-V on the new Windows 10 builds (Creators update) and this means Hyper-V will create checkpoints independently outside of the framework.
This is a fix/workaround to disable automatic checkpoints on the VM right after the it is created.
Reference: https://blogs.technet.microsoft.com/virtualization/2017/04/20/making-it-easier-to-revert/

Disable automatic checkpoints on Hyper-V VMs

---

Testscripts/Linux/CORE-CPUVerifyOnline.sh
Testscripts/Linux/KVP-BasicChecks.sh
Testscripts/Linux/NET-Copy-Large-File.sh
Testscripts/Linux/STOR-Large-CopyFile.sh
Testscripts/Linux/STORAGE-HotRemove.sh
Testscripts/Linux/STORAGE-LargeDisk.sh
Testscripts/Linux/Sysbench.sh
Testscripts/Linux/utils.sh

Various code cleanup and fixes:
- Removed sourcing of constants.file (it is performed by default in UtilsInit function)
- Fixed a few occurences of /root folder being used instead of /home/$user
- Fixed GetOSVersion function in utils.sh
- Removed whitespaces
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:5
1 KVP-BASIC-CHECKS                                                                  PASS                 3.12
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : …

Testscripts: Various fixes in bash scripts

---

Libraries/HyperV.psm1

On HyperV platform, if any live migration test is run on a non-clustered environment, LISAv2 exits with 1 and does not continue with running the remaining test cases.
This patch fixes the above issue and makes sure the parent vhd is cached in the cluster storage directory so that live migration succeeds.
**LISAv2 is required to run on a cluster node, otherwise, credssp and username/password needs to be provided somehow (and there is no support yet in the framework for this feature).** 
**Multiple live migration test cases need to be run with LISAV2 flag: -DeployVMPerEachTest:$true, otherwise only the first one will PASS.**
Execution tested:
```
VHD Under Test        : ubuntu_18.04.1\ubuntu_18.04.1.vhdx
Test Area             : MIGRATION
Total Test Cases      : 10 (10 Passed, 0 Failed, 0 …
```

HyperV: Abort TC if the server is not in a cluster

---

XML/TestCases/CommunityTests.xml
XML/TestCases/FunctionalTests-NVME.xml

'nobarrier' mount option is not supported on some distros with xfs filesystem
Removed TEST_FS_MOUNT_OPTS from XML files (NVME and Community tests) for XFS/Generic test cases.
FILE-SYSTEM-VERIFICATION-TESTS-GENERIC                                            FAIL                 6.14 
FILE-SYSTEM-VERIFICATION-TESTS-XFS                                                FAIL                 6.55 
root@LISAv2-OneVM1Disk-staging-TG25-20190226080244-role-0:/home/lisa/xfstests# ./check -g generic/quick -E exclude.txt
mount: /root/test: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper program, or other error.
common/rc: retrying test device mount with external set
mount: /root/test: wrong fs type, bad option, bad superblock on /dev/sdc1, missing codepage or helper …

xfstests: Removed mount options for XFS FS

---

Libraries/HyperV.psm1

Issue #786 
When running the tests from Server A on Server B, Join-Path command was failing, if there was drive mismatch. 
---

HyperV: Fix: join-path fails in case of mismatched drives between LISAv2 executor and Server under test

---

Testscripts/Linux/utils.sh

In ubuntu/debian we might get a package install prompt that will make the fio test hang.
Adding this variable solves this.
Get:8 http://azure.archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu/ trusty-updates/main postfix amd64 2.11.0-1ubuntu1.2 [1,088 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu/ trusty/main sysstat amd64 10.2.0-1 [283 kB]
Preconfiguring packages ...
root@LISAv2~# cat TestExecution.log
Fri Mar 01 11:57:38 2019 : Warning: summary file /root/summary.log either does not exist or is not a regular file. Trying to create it...
Fri Mar 01 11:57:38 2019 : **install_fio: Success**
Fri Mar 01 11:57:38 2019 : INFO: Check and remove RAID first
Fri Mar 01 11:57:38 2019 : INFO: Creating Partitions
---

install_fio: Added noninteractive var

---

Testscripts/Windows/SRIOV-DISABLEVF-IPERF.ps1
Testscripts/Windows/SRIOV-DISABLEVF-ONHOST.ps1
Testscripts/Windows/SRIOV-DISABLEVF-PING.ps1

Following test case discussions, it was agreed that we need to disable VF on dependency VMs too, not only on the main VMs. This changes all "DISABLEVF" SR-IOV Hyper-V scripts by disabling the VF on the dependency VM. This helps getting bigger deltas between SR-IOV disabled and enabled
02/20/2019 14:06:34 : [INFO ] The throughput before disabling SR-IOV is 19.4 Gbits/sec
02/20/2019 14:09:13 : [INFO ] **The throughput with SR-IOV disabled is 14.3 Gbits/sec**
02/20/2019 14:10:50 : [INFO ] The throughput after re-enabling SR-IOV is 18.6 Gbits/sec
03/05/2019 08:21:54 : [INFO ] The throughput before disabling SR-IOV is 14.1 Gbits/sec
03/05/2019 08:22:31 : [INFO ] **The throughput with SR-IOV disabled is 7.76 Gbits/sec**
03/05/2019 08:23:07 : [INFO ] The throughput after re-enabling SR-IOV is …

SR-IOV: Disable VF on dependency VM (Hyper-V)

---

Testscripts/Linux/dpdk_generic_setup.sh
Testscripts/Linux/ovs_setup.sh

Small fixes for the OVS DPDK functional test, making sure the installation fails if an exit code is non zero.
---

dpdk_ovs: exit on failure

---

Testscripts/Linux/dpdkSetup.sh
Testscripts/Linux/dpdk_generic_setup.sh
Testscripts/Linux/ovs_setup.sh

Enable dpdk and ovs setup on Ubuntu 16.04.
Fixes the rest of dpdk tests when using a git repo as dpdk source.
---

dpdk: enable dpdk_ovs on Ubuntu 16 and fix dpdkSetup.sh with git repos
